server:
  port: 8090

spring:
  application:
    name: ysyapi-gateway
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 0
    redisson:
      file: classpath:redisson.yml
  # spring cloud 配置
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
  # rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest



logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
  charset:
    console: UTF-8

dubbo:
  application:
    name: dubbo-springboot-demo-consumer
    qos-enable: true
    qos-port: 33333
    qos-accept-foreign-ip: true
  registry:
    address: nacos://localhost:8848